In [79]:
%pip install numpy

In [1]:
import numpy as np

## Multidimensional Arrays with Numpy


Numpy arrays can be multidimensional: they can be squares, cubes, hypercubes, etc!  When choosing datastructures, Arrays are best chosen when all of the values in the structure represent the same variable.

With multidimensional arrays, everything is pretty much the same as the 1-dimensional case, with the addition of a few options for specifiying which order the dimensions should be in, and which dimension an operation should operate on.

### Creating Multidimensional Arrays

Most of the array-generation functions have a **shape** or **size** optional argument in them.  If you provide a tuple with a new shape specifying the number of elements along each dimension (e.g. (5, 3) will produce a matrix with 5 rows and 3 columns), it will give you something multidimensional!

```python
>>> data = np.random.randint(1, 10, size=(4, 5))
>>> data
array([[9, 7, 4, 2, 3],
       [3, 6, 7, 4, 8],
       [3, 6, 8, 7, 3],
       [6, 9, 4, 2, 2]])
```

| Method | Function | Description | Example |
| :-- | :-- | :-- | :-- | 
| **`arr.shape`** | `np.shape(arr)` | Gets the shape of an array  | `arr.shape` |
| **`arr.reshape(shape)`** | `np.reshape(arr, shape)` | Makes an array with a new shape. | `arr.reshape(3, 10)` |
| **`arr.flatten()`** |  | Makes an array one-dimensional | `arr.flatten()` |
| **`arr[:, None]`** |  | Add an empty column dimension | `arr[:, None]` |
| **`arr[None, :]`** |  | Add an empty row dimension | `arr[None, :]` |


**Exercises**

*Example*: Make this list of lists of integers into a two-dimensional array:

In [2]:
data = [[1, 2, 3], [4, 5, 6]]
data

[[1, 2, 3], [4, 5, 6]]

In [3]:
arr = np.array(data)
arr

array([[1, 2, 3],
       [4, 5, 6]])

Make this list of lists of floats into a two-dimensional array:

In [4]:
data = [[1.1, 10.2], [-3.2, -3.4], [2.7, 100.1]]

*Example*: Generate a 4 x 5 array of random integers between 10 and 20 using **`np.random.randint`**

In [3]:
np.random.randint(10, 21, size=(4, 5))

array([[20, 18, 19, 20, 13],
       [10, 18, 15, 20, 14],
       [10, 16, 19, 15, 16],
       [17, 12, 14, 18, 20]])

Generate a 3 x 10 array of random integers between 1 and 4 using **`np.random.randint`**

Make a flat array with all the values between 0 and 11, and then reshape it into a 3 x 4 matrix using **`array.reshape()`**

...Reshape the previous array into a 4 x 3 matrix...

...Reshape that array into a 2 x 6 matrix...

...Then flatten it.

### Reordering Dimensions
| Method | Function | Description | Example |
| :-- | :-- | :-- | :-- |
| **`arr.T`** |  | Transpose an array | `arr.T` |
| **`arr.transpose()`** | `np.transpose(arr)` | Transpose an array | `arr.transpose()` |
| **`arr.swapaxes(dim1, dim2)`** | `np.swapaxes(dim1, dim2)` | Transpose an array  | `arr.swapaxes(0, 1)` |




**Exercises**
Use each of the four above transpose functions on the following array **x**.

In [4]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

### Aggregating Across Axes

| Function | Method |
| :---  | :--- |
| `np.mean(x, axis=0)` | `x.mean(axis=0)` |
| `np.std(x, axis=0)`  | `x.std(axis=0)`  |
| `np.median(x, axis=0)` | *(No median method)* |

Almost all of the Numpy aggregation functions have an **axis** option, which lets you limit the operation to just that axis.  

For example, to get the mean of all columns:

```python
>>> array = np.arange(12).reshape(3, 4)
>>> array.mean(axis=0)
array([4., 5., 6., 7.])
```

And the mean of the rows:

```python
>>> array.mean(axis=1)
array([1.5, 5.5, 9.5])
```

Notice that the number of dimensions goes down by default whenever you aggregate across the axis.  If you'd like to keep the dimensions the same, you can also use the **keepdims=True** option:

```python
>>> array.mean(axis=1, keepdims=True)
array([[1.5],
       [5.5],
       [9.5]])
```

**Exercises**: Try it out for yourself, with the provided array `data`:

In [3]:
np.random.seed(42)
data = np.random.randint(0, 10, size=(5, 3)) * [1, 10, 100]
data

array([[  6,  30, 700],
       [  4,  60, 900],
       [  2,  60, 700],
       [  4,  30, 700],
       [  7,  20, 500]])

*Example*: What is the mean of each column?

In [23]:
data.mean(axis=0)

array([  4.6,  40. , 700. ])

What is the standard deviation of each row?

What is the maximum of each column?

What is the mean of each column's median?

What is the standard deviation of all the numbers in the matrix?

What is the maximum of each row?

## Extra Credit: Building Matrices from Existing Arrays

Numpy has a staggering number of functions specifically made just for concatenating arrays together, and it's possible to use most of them to get the same result. Here are a few we'll try:

| Function | Description |
| :-- | :-- |
| `np.stack(a, b)` | concatenates two arrays, adding a new axis to the resulting matrix | 
| `np.column_stack(a, b)` | concatenates two 1D arrays, making each a column in the new matrix |
| `np.row_stack(a, b)` | concatenates two 1D arrays, making each a row in the new matrix |
| `np.concatenate((a, b))` | concatenates N arrays along an existing axis |
| `np.append((a, b))` | concatenates N arrays, extending out an existing axis |

Note that each of these functions:
  - **Expects Either Two Arrays or One Tuple of Arrays**:
  - **Has Different Default Axis Behaviors**: You can override them with the classic `axis=0` or `axis=1` to get a different result.
  - **May or May Not Create a New Dimension in the Result**: You can quickly add a new dimension to an array by either:
    - *Putting it in a list, for numpy to change into an array*: e.g. `np.concatenate(([aa], [bb]))`
    - *Indexing None on a dimension to have numpy create one*: e.g. `aa[:, None]` or `aa[None, :]`
  - **Transposing in Numpy is Computationally Free**: 




**Exercises**:  Using the two 1D arrays `aa` and `bb`, concatenate them together using only the requested function to get the requested matrix shape.  Reminder, you may have to use some of the tricks above to get some of these functions to work)
Let's try these functions out, working around each of their default behaviors to get the result we want.


In [7]:
aa = np.arange(5)
bb = np.arange(10, 15)

Use `np.stack()` to make a (2 x 5) matrix from `aa` and `bb`

Use `np.stack()` to make a (5 x 2) matrix from `aa` and `bb`

Use `np.column_stack()` to make a (2 x 5) matrix from `aa` and `bb`

Use `np.column_stack()` to make a (5 x 2) matrix from `aa` and `bb`

Use `np.row_stack()` to make a (2 x 5) matrix from `aa` and `bb`

Use `np.row_stack()` to make a (5 x 2) matrix from `aa` and `bb`

Use `np.concatenate()` to make a (2 x 5) matrix from `aa` and `bb`

Use `np.concatenate()` to make a (5 x 2) matrix from `aa` and `bb`

Use `np.append()` to make a (2 x 5) matrix from `aa` and `bb`

Use `np.append()` to make a (5 x 2) matrix from `aa` and `bb`